"""Shared runtime primitives for Hermes location-aware skills."""

from .context import (
    ContextConfig,
    ContextEvidence,
    ContextResult,
    ContextStatus,
    ContextTrait,
    ContextUncertainty,
    CurrentContext,
    CurrentContextEngine,
    Freshness,
    FreshnessThresholds,
)
from .context_inputs import (
    ContextInputBundle,
    ContextInputIssue,
    ContextInputLoader,
    build_location_source_resolver,
)
from .contracts import (
    AlertDecision,
    GateDecision,
    LocationSample,
    ProviderResult,
    RouteGeometry,
)
from .location_sources import (
    HttpOwnTracksReceiver,
    LocationObservation,
    LocationSource,
    LocationSourceResolver,
    LocationSourceResult,
    LocationStatus,
    OwnTracksLocationSource,
    ReplayLocationSource,
    TelegramLocationSource,
    canonical_device_id_from_env,
    parse_source_order,
)
from .movement import (
    DataQuality,
    EngineState,
    MovementConfig,
    MovementEngine,
    MovementEvent,
    MovementEventType,
    MovementMode,
    MovementResult,
    MovementSegment,
    MovementState,
    ProcessingStatus,
)
from .movement_state import MovementStateRepository
from .output_safety import navigation_url, safe_label, safe_prose
from .place import (
    MatchStatus,
    Place,
    PlaceConfig,
    PlaceEngine,
    PlaceEngineState,
    PlaceEvent,
    PlaceEventType,
    PlaceMatch,
    PlaceProcessingStatus,
    PlaceResult,
    PlaceStatus,
    PlaceVisit,
    Stay,
    StayStatus,
)
from .place_state import PlaceStateRepository
from .providers import ProviderRegistry
from .repository import CorruptStateError, JsonStateRepository

StateRepository = JsonStateRepository

__all__ = [
    "AlertDecision",
    "CorruptStateError",
    "ContextConfig",
    "ContextEvidence",
    "ContextInputBundle",
    "ContextInputIssue",
    "ContextInputLoader",
    "ContextResult",
    "ContextStatus",
    "ContextTrait",
    "ContextUncertainty",
    "CurrentContext",
    "CurrentContextEngine",
    "Freshness",
    "FreshnessThresholds",
    "build_location_source_resolver",
    "GateDecision",
    "JsonStateRepository",
    "LocationSample",
    "LocationObservation",
    "LocationSource",
    "LocationSourceResolver",
    "LocationSourceResult",
    "LocationStatus",
    "DataQuality",
    "EngineState",
    "MovementConfig",
    "MovementEngine",
    "MovementEvent",
    "MovementEventType",
    "MovementMode",
    "MovementResult",
    "MovementSegment",
    "MovementState",
    "MovementStateRepository",
    "ProcessingStatus",
    "MatchStatus",
    "Place",
    "PlaceConfig",
    "PlaceEngine",
    "PlaceEngineState",
    "PlaceEvent",
    "PlaceEventType",
    "PlaceMatch",
    "PlaceProcessingStatus",
    "PlaceResult",
    "PlaceStateRepository",
    "PlaceStatus",
    "PlaceVisit",
    "Stay",
    "StayStatus",
    "HttpOwnTracksReceiver",
    "OwnTracksLocationSource",
    "ReplayLocationSource",
    "TelegramLocationSource",
    "canonical_device_id_from_env",
    "parse_source_order",
    "ProviderRegistry",
    "ProviderResult",
    "RouteGeometry",
    "StateRepository",
    "navigation_url",
    "safe_label",
    "safe_prose",
]
